### ISSUE TITLE
Failed install on windows 10 using Python 9

### ISSUE THREAD

**Issue by pviljoen2** [mu-editor/mu-editor.github.io#63]
Traceback (most recent call last):
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

*** Note cannot find place to [upload]([mu.log](https://github.com/mu-editor/mu-editor.github.io/files/6470001/mu.log)) log file****

**Comment by ajs256** [comment]
Hey there @pviljoen2, 

This is the repository for Mu's website. I've opened an issue in Mu's code repository (https://github.com/mu-editor/mu/issues/1641), so the conversation will move there.
